# Generated by Django 4.2.1 on 2023-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='log_text',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='message',
            field=models.CharField(default='message', max_length=100),
        ),
    ]
