# Generated by Django 4.2.1 on 2023-06-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_tasklog_log_text_tasklog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='list.task'),
        ),
    ]
