# Generated by Django 4.2.1 on 2023-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_tasklog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('FINALIZED', 'Finalizada')], default='IN_PROGRESS', max_length=20),
        ),
    ]
