# Generated by Django 4.2.1 on 2023-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída')], default='IN_PROGRESS', max_length=20),
        ),
    ]
